# Generated by Django 3.0.8 on 2020-07-20 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('strategy', 'Strategy'), ('deckbuilding', 'Deckbuilding'), ('rpg', 'RPG'), ('coop', 'Co-op')], max_length=20)),
                ('max_players', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New PlayerSet', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p1', to='leaderboard.Player')),
                ('player10', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p10', to='leaderboard.Player')),
                ('player2', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p2', to='leaderboard.Player')),
                ('player3', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p3', to='leaderboard.Player')),
                ('player4', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p4', to='leaderboard.Player')),
                ('player5', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p5', to='leaderboard.Player')),
                ('player6', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p6', to='leaderboard.Player')),
                ('player7', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p7', to='leaderboard.Player')),
                ('player8', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p8', to='leaderboard.Player')),
                ('player9', models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, related_name='playerset_p9', to='leaderboard.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boardgame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_boardgame', to='leaderboard.Boardgame')),
                ('players', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_playerset', to='leaderboard.PlayerSet')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_winner', to='leaderboard.Player')),
            ],
        ),
    ]
