# Generated by Django 3.0.8 on 2020-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='genres',
            field=models.ManyToManyField(related_name='genre_list', to='leaderboard.Genre'),
        ),
    ]
