# Generated by Django 3.0.8 on 2020-08-09 08:51

import apps.leaderboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=100, validators=[apps.leaderboard.validators.validate_unique_boardgame]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20, validators=[apps.leaderboard.validators.validate_unique_genre]),
        ),
    ]
